/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import static java.lang.Integer.parseInt;

/**
 *
 * @author cuozz
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Uno = new javax.swing.JButton();
        Piu = new javax.swing.JButton();
        Tre = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Quattro = new javax.swing.JButton();
        Meno = new javax.swing.JButton();
        Due = new javax.swing.JButton();
        Per = new javax.swing.JButton();
        Cinque = new javax.swing.JButton();
        Sette = new javax.swing.JButton();
        Sei = new javax.swing.JButton();
        Otto = new javax.swing.JButton();
        Nove = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Titolo = new javax.swing.JLabel();
        Diviso = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        Uguale = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        Uno.setText("1");
        Uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoActionPerformed(evt);
            }
        });

        Piu.setText("+");

        Tre.setText("3");
        Tre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreActionPerformed(evt);
            }
        });

        jTextField1.setText("Input something");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Quattro.setText("4");
        Quattro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuattroActionPerformed(evt);
            }
        });

        Meno.setText("-");
        Meno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenoActionPerformed(evt);
            }
        });

        Due.setText("2");
        Due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueActionPerformed(evt);
            }
        });

        Per.setText("*");

        Cinque.setText("5");
        Cinque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CinqueActionPerformed(evt);
            }
        });

        Sette.setText("7");

        Sei.setText("6");

        Otto.setText("8");

        Nove.setText("9");

        Zero.setText("0");

        Titolo.setText("C A L C U L A T O R");

        Diviso.setText("/");

        Clean.setText("CE");
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        Uguale.setText("=");
        Uguale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UgualeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titolo)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Quattro)
                                .addComponent(Uno)
                                .addComponent(Sette))
                            .addComponent(Clean))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Due)
                                    .addGap(18, 18, 18)
                                    .addComponent(Tre))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Cinque)
                                    .addGap(18, 18, 18)
                                    .addComponent(Sei))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Otto)
                                        .addComponent(Zero))
                                    .addGap(18, 18, 18)
                                    .addComponent(Nove)
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Meno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Piu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Per, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Diviso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(Uguale, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Titolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Uno)
                    .addComponent(Tre)
                    .addComponent(Due)
                    .addComponent(Piu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quattro)
                    .addComponent(Cinque)
                    .addComponent(Sei)
                    .addComponent(Meno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sette)
                    .addComponent(Otto)
                    .addComponent(Nove)
                    .addComponent(Per))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Zero)
                    .addComponent(Diviso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clean)
                    .addComponent(Uguale))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Uno.getAccessibleContext().setAccessibleName("UNO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String res = "";
    int intero = 0;
        
    void setResNull(){
        res = "";
    }
        
    void setRes(String x){
        res = res + x;
    }
    
    void toInt(){
        intero = parseInt(res,10);
    }
    
    private void UnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoActionPerformed
        // TODO add your handling code here:
        //System.out.println(1);
        setRes("1");
        System.out.println(res);
        toInt();
    }//GEN-LAST:event_UnoActionPerformed

    private void TreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TreActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void QuattroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuattroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuattroActionPerformed

    private void DueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueActionPerformed
        // TODO add your handling code here:
        //System.out.println(1);
        setRes("2");
        System.out.println(res);
        toInt();
    }//GEN-LAST:event_DueActionPerformed

    private void CinqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CinqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CinqueActionPerformed

    private void MenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenoActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // TODO add your handling code here:
        setResNull();
    }//GEN-LAST:event_CleanActionPerformed

    private void UgualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UgualeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UgualeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cinque;
    private javax.swing.JButton Clean;
    private javax.swing.JButton Diviso;
    private javax.swing.JButton Due;
    private javax.swing.JButton Meno;
    private javax.swing.JButton Nove;
    private javax.swing.JButton Otto;
    private javax.swing.JButton Per;
    private javax.swing.JButton Piu;
    private javax.swing.JButton Quattro;
    private javax.swing.JButton Sei;
    private javax.swing.JButton Sette;
    private javax.swing.JLabel Titolo;
    private javax.swing.JButton Tre;
    private javax.swing.JButton Uguale;
    private javax.swing.JButton Uno;
    private javax.swing.JButton Zero;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
